### ISSUE TITLE
refactor localization

### ISSUE THREAD

**Issue by danieleades** [tobealive/wthrr-the-weathercrab#109]
the localisation is clever but i think it could be improved by caching the translations locally, rather than re-fetching them every time.

though to be honest, for the cost of a few extra strings in the compiled binary, it might be better again to consider generating the localisation at compile time.

both are relatively simple to implement. what do you think @tobealive?

**Comment by tobealive** [comment]
Hey @danieleades,

Thanks for reaching out and aiming to improve this!
Currently, when a user saves a languages, the translation is saved in `weathercrab/locales/<langcode>.json` so it won't be re-fetched and translated strings can be customized.  

But I'm 100% open for improvements. Could you elaborate a bit about the outcome?

**Comment by tobealive** [comment]
I'm gonna close this due to inactivity. Please let me know if something more comes up and we can pull it back up.
