### ISSUE TITLE
Nix sandbox causes build to fail

### ISSUE THREAD

**Issue by jeiang** [tobealive/wthrr-the-weathercrab#115]
Tests which access the internet (`modules::localization::tests::translate_string` and `modules::location::tests::geolocation_response`) fail when building on nix due to the nix sandbox.

If the sandbox is disabled (either in nix.conf or by using `--no-sandbox`), the cacert package needs to be added (see [this comment](https://github.com/NixOS/nixpkgs/issues/66716#issuecomment-883399373))
<details>
<summary>Relevant snippet of the logs</summary>

```
   Finished release [optimized] target(s) in 14.35s
     Running unittests src/main.rs (target/x86_64-unknown-linux-gnu/release/deps/wthrr-bf0b90047fd425ed)

running 9 tests
test modules::forecast::tests::forecast_indices ... ok
test modules::forecast::tests::index_form_day ... ok
test modules::location::tests::address_from_cfg ... ok
test modules::location::tests::address_from_arg ... ok
test modules::units::tests::units_from_cfg ... ok
test modules::units::tests::units_from_args ... ok
test modules::units::tests::units_split_from_args_and_cfg ... ok
test modules::localization::tests::translate_string ... FAILED
test modules::location::tests::geolocation_response ... FAILED

failures:

---- modules::localization::tests::translate_string stdout ----
Error: error sending request for url (https://translate.googleapis.com/translate_a/single?client=gtx&ie=UTF-8&oe=UTF-8&dt=t&sl=en
_US&tl=de_DE&q=tongue-twister): error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certific
ate verify failed:ssl/statem/statem_clnt.c:1889: (unable to get local issuer certificate)

Caused by:
    0: error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/sta
tem/statem_clnt.c:1889: (unable to get local issuer certificate)
    1: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (
unable to get local issuer certificate)
    2: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:

---- modules::location::tests::geolocation_response stdout ----
Error: error sending request for url (https://geocoding-api.open-meteo.com/v1/search?name=berlin&language=de): error trying to co
nnect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (
unable to get local issuer certificate)

Caused by:
    0: error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/sta
tem/statem_clnt.c:1889: (unable to get local issuer certificate)
    1: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (
unable to get local issuer certificate)
    2: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:


failures:
    modules::localization::tests::translate_string
    modules::location::tests::geolocation_response

test result: FAILED. 7 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.99s

error: test failed, to rerun pass `--bin wthrr`
```
</details>

Alternatively, those tests could be disabled in the flake, so that the build succeeds without having to pass `--no-sandbox`.

**Comment by jeiang** [comment]
I made the two possible fixes, ((skipping the tests)[https://github.com/jeiang/wthrr-the-weathercrab/tree/update-flake] and (no-sanbox)[https://github.com/jeiang/wthrr-the-weathercrab/tree/no-sandbox-build]).

The first one can be run using `nix run github:jeiang/wthrr-the-weathercrab/update-flake`, the second by `nix run github:jeiang/wthrr-the-weathercrab/no-sandbox-build --no-sandbox`. 

Let me know if either is good and I'll make a PR.

**Comment by tobealive** [comment]
Thanks for the work @jeiang!

I have to admit that I didn't had the chance to get deep into nix yet. Would you as a nix user prefer having the additional `cacert` dependency in there?

Else I'd say skipping the tests on nix to keep it sandboxed is fine as we'd still get indicators from CI an on other platforms.

**Comment by jeiang** [comment]
I'm fine with the `cacert` dependency, since its build time only, however I think the skip tests option is better, since CI will catch test failures. Additionally, [the sandbox is enabled by default on Linux & Nixos](https://nixos.wiki/wiki/Nix_package_manager#Sandboxing), so simply disabling the tests allows everyone to run it without having to either modify their system conf or pass the `--no-sanbox` flag.

I'll make the PR for skipping tests.
