### ISSUE TITLE
Add option(s) to ignore saved address

### ISSUE THREAD

**Issue by jeiang** [tobealive/wthrr-the-weathercrab#125]
Basically, an option that ignores the saved address, so that it checks for a city near current location (such as the default behavior when a location isn't specified and one isn't provided on the command line).

**Comment by tobealive** [comment]
Hey @jeiang there is

```
wthrr auto
```

Auto behaves a special input here.
Is this what your are looking for?

**Comment by jeiang** [comment]
Yes it was, hadn't seen it since I last checked the page. Sorry about that!
