### ISSUE TITLE
[Suggestion] tomorrow

### ISSUE THREAD

**Issue by GalSoft** [tobealive/wthrr-the-weathercrab#132]
It would be great to get the detailed forecast for "tomorrow"

**Comment by kevinmatthes** [comment]
@tobealive @GalSoft

I am working on a concrete suggestion for an implementation.  I will submit a PR in few hours.

**Comment by kevinmatthes** [comment]
I just submitted my suggestion as #136.  @GalSoft, please have a look at the changes and add some feedback if the changes fit your requirements.
