### ISSUE TITLE
[Suggestion] Further README Badges

### ISSUE THREAD

**Issue by kevinmatthes** [tobealive/wthrr-the-weathercrab#148]
@tobealive

There are four further badges I would like to add to the README:

1. total downloads of Wthrr
2. status of the documentation on docs.rs
3. license of this repository
4. last commit

Which of them would you consider useful?

**Comment by tobealive** [comment]
Lets go with No. 4.
For me, simplicity is the preference here. When it comes to documentation, there is just the readme file, and the license is nicely displayed on GitHub and crates.to in the sidebars.

**Comment by kevinmatthes** [comment]
Okay, I will prepare the changes. :+1:

By default, I would configure the badge as a Markdown link rather than using the explicit HTML syntax which is used, at the moment.  Shall I rather continue with the current style or simplify the other two badges to the shorter Markdown syntax?

**Comment by tobealive** [comment]
Please stay with HTML. If I recall it right, the nit it is used, is that it was possible to slightly increase the spacing. In markdown, adding the `<br>`  would make the spacing too big, while not having it is just a regular line break which is to little.
