### ISSUE TITLE
dns error

### ISSUE THREAD

**Issue by ket000** [tobealive/wthrr-the-weathercrab#16]
Trying to run this in WSL on Windows 10 gives below error.

 wthrr
✔ You didn't specify a city. Should I check for a weather station close to your location? · yes
Error: error sending request for url (https://api.geoip.rs/): error trying to connect: dns error: failed to lookup address information: Name or service not known

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: Name or service not known
    1: dns error: failed to lookup address information: Name or service not known
    2: failed to lookup address information: Name or service not known

nslookup api.geoip.rs

Non-authoritative answer:
Name:   api.geoip.rs
Address: 176.58.108.133

Resolves it correctly.

**Comment by tobealive** [comment]
Thanks for reporting the issue @ket000,

I check on it soon! 
Currently it's a bit of back and for between two new projects at work. But finding the time to put more work into personal projects is also in the making :+1:

**Comment by ket000** [comment]
Thanks for the response. I believe it is looking for something in WSL distro which it does not have. If there is a package dependency, I can install it. I am using Oracle Linux 7.9 for WSL distro.

**Comment by tobealive** [comment]
Hey @ket000 

Unfortunately, I could not reproduce it successfully.
Yesterday I "accidentally" encountered this error. But when I tried again, it worked. 

The free API from geoip that we use here might be reaching its limits at some times.
Does this happen every time you try to resolve the address automatically?

**Comment by ket000** [comment]
It's working fine now. Not sure if something changed as I routinely update rust components. So we seems to be good. Thanks for looking into it.

**Comment by tobealive** [comment]
Thanks for reporting back. Good to hear that it works now!
