### ISSUE TITLE
[Suggestion] Renovate?

### ISSUE THREAD

**Issue by kevinmatthes** [tobealive/wthrr-the-weathercrab#172]
@tobealive

Dependabot is not the sole GitHub App to search for and suggest updates as PRs, one possible alternative is Renovate.  It has plenty of configuration options and capabilities such that also `cargo update` PRs are possible.  Furthermore, I hope that this *might* solve the Dependabot commit message issue as there are detailed and explicit configuration options for the commit message such that the desired format *should* be possible.  (I emphasised the *might* and *should* parts because I am new to Renovate and still trying to get into the configuration options in depth but even now, I assume that the intended style should be easier configurable than with Dependabot.)

What do you think about this option; would you like to give Renovate a try?

**Comment by tobealive** [comment]
Thanks for the suggestion @kevinmatthes 

I'm scheduling in some hours for the repo - for now on one day a month -. When it's just by chance I'm too flaky with it and don't manage to put in maintenance time. There is always an open source project with open changes. 
On the list for wthrr I also had debugging dependabot and submitting the fix, I think the suggestions you made there were a good starting point so I would utilize this.
If you already have a setup that would be easy to adapt, we can also try renovate :+1:

**Comment by kevinmatthes** [comment]
@tobealive

I think we should give Dependabot a second chance, then.  In the meantime, I will do some further research on the configuration of Renovate such that we could still switch to it, if required.

**Comment by ttytm** [comment]
Hey @kevinmatthes!
I hope you are doing well.

From how the bots worked in the last weeks, can one of the dependency bots be removed?

**Comment by ttytm** [comment]
Okay great, then lets remove Dependabot. Adding fine tuning the  renovate settings to include the validator is good as well :+1:.

**Comment by kevinmatthes** [comment]
The linter: #247.

**Comment by kevinmatthes** [comment]
Removing Dependabot:  #250.
