### ISSUE TITLE
After upgrade to 0.4.1 running it gives : Bad TOML data

### ISSUE THREAD

**Issue by ket000** [tobealive/wthrr-the-weathercrab#28]
wthrr
Error: Bad TOML data

Caused by:
    invalid type: string "celsius,kmh", expected struct Units for key `units` at line 2 column 9

cat wthrr.toml
address = 'NewYork,US'
units = 'celsius,kmh'
greeting = true
language = 'en'

Looks like toml format has changed. 

To fix, I need to delete the file and edit it again.

**Comment by tobealive** [comment]
Hey @ket000,

sorry for the inconvenience after the upgrade.

This breaking change was introduced with 70fabdbba0b3c0fcc0e45f6ce24771371d7b9c0c and is documented for [v0.4.0](https://github.com/tobealive/wthrr-the-weathercrab/releases/tag/v0.4.0).

You probably have upgrade from an older version. I hope it works again now.
