### ISSUE TITLE
panics when providing `-g` option

### ISSUE THREAD

**Issue by arctic-penguin** [tobealive/wthrr-the-weathercrab#32]
* version: 0.4.1
* installed via cargo

```
$ wthrr -g
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/wthrr-0.4.1/src/modules/params/greeting.rs:9:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by arctic-penguin** [comment]
Just found this happens when the `greeting` option in `wthrr.toml` is unspecified.

**Comment by tobealive** [comment]
Good catch @arctic-penguin 

Looks like must have missed including a fall back to the default config in when unwrapping the value. 
 
Thanks for pointing this out. I'll check your PR.
