### ISSUE TITLE
Clarify Config Locations for Non-GNU/Linux in README.md

### ISSUE THREAD

**Issue by ijoseph** [tobealive/wthrr-the-weathercrab#73]
Would have saved me some time to have, in addition to the linux location, the other OS' default config locations in the main README:

Lin: `/home/<user>/.config/weathercrab`
Win: `C:\Users\<user>\AppData\Roaming\weathercrab`
Mac: `/Users/<user>/Library/Application Support/weathercrab`

Especially as the Linux location is an actually reasonable place to put things on macOS.

**Comment by hasnolen** [comment]
Also, trailing slashes to indicate that this is the directory that `wthrr.ron` needs to **live** in, not the name of the actual `.ron`.

**Comment by tobealive** [comment]
Hey peeps, thanks for reaching out. 

Yes, currently those paths are only in https://github.com/tobealive/wthrr-the-weathercrab/blob/main/wthrr.ron (trailing slashes missing).

Readme will be extended and trailing slashes added :+1:
