### ISSUE TITLE
Native NetBSD package

### ISSUE THREAD

**Issue by 0323pin** [tobealive/wthrr-the-weathercrab#8]
Hi,
I've just packages `wthrr` for NetBSD :)

![2022-08-14-223459_1366x768_scrot](https://user-images.githubusercontent.com/90570748/184554081-f271b4f6-4284-4c6c-89e3-84ea3e61d65e.png)

Before I merge it into our repositories, I'd like to ask how should we name the package. Simply `wthrr` like the binary or, the full name `wthrr-the-weathercrab`?
Also, please don't hide `Cargo.lock`, we have a script that reads it and automatically fetches all the dependencies. If it's hidden, I need to do it manually. Thanks!

**Comment by tobealive** [comment]
Hello :)

Nice, thanks for your work and request!  It's great that you do some clarifications beforehand; it makes fewer compilations in the long run.  

Let's go with just `wthrr` that's the crates name after all. Yes, cargo lock is visible! A contributor made a nice nix integration, and it was also required.

**Comment by 0323pin** [comment]
@tobealive Thanks for clearing that out. Merged, http://mail-index.netbsd.org/pkgsrc-changes/2022/08/15/msg258446.html

Feel free to close this issue.
