### ISSUE TITLE
Panic on first run

### ISSUE THREAD

**Issue by Kl4rry** [tobealive/wthrr-the-weathercrab#81]
The first time the application is run it prompts the user to pick a location. When it then tries to save the location to file it panics.
Platform: Windows
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "Det går inte att hitta sökvägen." }'

**Comment by atomic1fire** [comment]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', C:\Users\USERNAME\.cargo\registry\src\github.com-1ecc6299db9ec823\wthrr-0.10.0\src\modules\config.rs:82:37

Same error.

I don't think it's writing a config file, and the path is nonexistant.

I installed via cargo.

**Comment by tobealive** [comment]
Thanks for reaching out! I'll investigate on this after getting some sleep.

Until then - from looking at the error and the code it points to - what you mention should work as a workaround. For windows it is
`C:\Users\<user>\AppData\Roaming\weathercrab\`.
The config section in the Readme got all the paths.

You can try creating just the weathercrab directory without a config file and let me know if it works. 
Else an empty `wthrr.ron`. There is also one with default values in the root of the repo.

**Comment by atomic1fire** [comment]
Manually creating the file/folder 

>%appdata%/weathercrab/wthrr.ron 

worked.

I just wasn't sure what folder it's supposed to be in.
