### ISSUE TITLE
Writing to config seems to fail first time

### ISSUE THREAD

**Issue by jewlexx** [tobealive/wthrr-the-weathercrab#83]
When I run the program, it looks for my city and then when I try to set that as my default, it throws the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', src\modules\config.rs:82:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It, seemingly, is trying to write to a config file, in a directory that does not exist, which is usually where this error comes from.

EDIT: Creating the directory removes the panic

**Comment by tobealive** [comment]
Hey, sorry for the inconvenience. The issue should be fixed in #82.

It's included in the latest release candidate. If installing the rc version from crates.io it's required to specify it `cargo install wthrr@^1.0.0-rc`

**Comment by jewlexx** [comment]
Sorry, I should have checked for closed issues first. 1.0.0-rc works

Thank you for your help

**Comment by tobealive** [comment]
No worries. Thanks to you!
