### ISSUE TITLE
[Suggestion] `cargo install --git`

### ISSUE THREAD

**Issue by kevinmatthes** [tobealive/wthrr-the-weathercrab#89]
In INSTALL.md, section "Build from source", you list the complete way to install Wthrr from the GitHub repository.  There is, however, also a shorter way using Cargo directly: `cargo install --git <repository URL>`.  See the official Cargo documentation (`cargo help install`) for further information.

Cargo will run the same steps in the background but for the end user, executing only one command with the same effect might be more convenient.

I would like to suggest to add this shorter installation method to INSTALL.md.

**Comment by tobealive** [comment]
Thanks a lot for the tip @kevinmatthes. And yes, sold!

Would you like to PR it or a mention :)?

**Comment by kevinmatthes** [comment]
Okay, I will submit a PR tomorrow.
