### ISSUE TITLE
[Suggestion] Dependabot

### ISSUE THREAD

**Issue by kevinmatthes** [tobealive/wthrr-the-weathercrab#90]
Dependabot helps to keep all dependencies up-to-date.  It can also be configured to use emojis as commit prefix.  Its suggested updates can be accepted by mailing it the respective instruction which is very useful to handle multiple Dependabot PRs without having to login to GitHub.

Would it be useful to enable it for this repository?

**Comment by tobealive** [comment]
Good suggestion. It would definitively be useful. I'll get into it this weekend.

**Comment by kevinmatthes** [comment]
Here is my suggestion for the setup:

```yaml
version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      time: '00:00'
    assignees:
      - tobealive
    commit-message:
      prefix: ':robot:'
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '00:00'
    assignees:
      - tobealive
    commit-message:
      prefix: ':robot:'
      include: scope
```

Just paste this to a new file named `.github/dependabot.yml`.  *You* need to do this because this is your repository; I once configured Dependabot for a project of another maintainer after agreeing with them on the configuration details.  It did not work because I as a contributor were not allowed to edit the repository settings.

Dependabot was a third party app, previously, but then, it became a feature of GitHub itself.  This is why you need "version: 2".  To activate Dependabot, it is sufficient to create its configuration file; this will activate Dependabot for this repository.  I assume it is a security feature that users without writing permission to a repository submitting valid Dependabot configurations are not going to trigger the automatic activation in order to not override the maintainers' privileges.

However, you need to configure the package registries to grab updates from; here, we only have GitHub Actions and Rust.  I copied this basic setup directly from one of my own projects using Dependabot, so I know that this works.  I left the update interval as it was:  Dependabot will search for new updates each day on UTC midnight.  Please note that there might be some delay if a crate publishes a new version which is a feature, again.  Dependabot will then skip intermediate releases, e.g. updates Clap v4.1.11 to v4.1.13 because it did not scan for updates when Clap v4.1.12 was published.  This behaviour is not critical as you can always scan for updates manually from the Insights tab of the repository.  Navigate to the "Dependency graph" section in the left side bar and select "Dependabot" from the three tabs of this section.  You will see a list of package registries found by Dependabot.  Click the link "Last checked ..." and confirm with the "Check for updates" button for each registry.  Dependabot will then scan for updates.

All updates are submitted as PRs.  You can either merge them manually by clicking the merge button or by commenting on the PR with the magic words "squash and merge", "rebase", or "merge" *after* a mention of Dependabot.  The commands are always described in the initial PR comment, authored by Dependabot.  Expand them and select the appropriate instruction.  This commenting feature allows for Mail Merging, i.e. writing an email to the PR with the magic words such that Dependabot will take care for the update without requiring you to login.  This is extremely useful if you have Dependabot set up for numerous repositories and an essential dependency like actions/checkout published a new release.

You will definitely receive an email to answer because I made you the assignee for each PR.  Please note that sometimes, Dependabot forgets to assign you.  This is very rare but might happen.  It is sufficient to answer the assignment notification.  You might need to experiment *how* to answer the first times; Thunderbird calls it "Reply to list", GMail apps will automatically reply to the correct message ID.  Some email providers also refuse to send identical emails so make sure that the original message is cited.

I also tried to configure the commit messages to fit this project's requirements.  The plain text emoji name will be rendered to the correct category's emoji on GitHub (according to #11); if you like, you can also insert the emoji directly.  I tried to do so myself but did not succeed because my fonts did not know the emoji.  The "include: scope" is useful to track the updates, Dependabot will name the PR something like "Bump clap from 4.2.0 to 4.2.1" after the configured :robot: prefix.

**Comment by tobealive** [comment]
Thanks a lot for the template @kevinmatthes!

I'll push the config today. One slight change I'll make is to increase the interval. Personally I don't like when repositories are artificially active by Dependabot bumps. Dependabot is a default for security updates anyway, so important notifications are sent anyway and discreetly. 

![Screenshot_20230402_140815](https://user-images.githubusercontent.com/34311583/229351997-3a7912bc-92a9-4ef6-bcec-1f7ea6fcb3bd.png)

**Comment by tobealive** [comment]
The commit and PR messages differ a bit from what is stated in the docs. E.g. the end of the following section shows `pip dev: bump requests from 1.0.0 to 1.0.1` as an example message.

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message

I didn't found if it's possible to move from 

`⬆️ (deps): Bump ...`

to

`⬆️ bump ...`.

So we keep conformity and a clean history with other commit messages.

If you have a clue on how to achieve it directly in `dependabot.yml` please feel free to share 😊. An actual github action would probably the alternative.
