### ISSUE TITLE
[Suggestion] CODEOWNERS

### ISSUE THREAD

**Issue by kevinmatthes** [tobealive/wthrr-the-weathercrab#93]
Reviewing PRs before accepting them is a good practice, especially in case of changes to security critical files.  GitHub repositories can be configured to automatically request someone if certain files were changed.  Therefore, a configuration file named `.github/CODEOWNERS` needs to be created appropriately.

With CODEOWNERS configured, the named people are always asked for review automatically when a new PR is submitted.  The user raising the PR does not need to select one or more reviewer(s) themselves when creating the PR because GitHub will select the respective users based on the CODEOWNERS settings.  In addition, merging is blocked automatically until *all* reviewers enforced by CODEOWNERS approved the PR.  **IMPORTANT:  This feature prevents from unlocking the GitHub achievement "YOLO".**

When using Dependabot on a repository with CODEOWNERS and preferring Mail Merging, I recommend to additionally configure Bors as it does not need to wait for all CODEOWNERS' approvals before merging a PR; instead, they can be mirrored to Bors' configuration file, at option, such that Mail Merging is still possible or can be processed differently.

@tobealive, are you interested?

**Comment by tobealive** [comment]
Sounds good :+1: 🙂

**Comment by kevinmatthes** [comment]
CODEOWNERS is configured as follows:

```
* @tobealive
```

This will trigger an automatic review request for every PR.  The positive side effect is that you will always receive a notification in case Dependabot should forget to assign you.

Just add this line to .github/CODEOWNERS and the feature is activated.

**Comment by tobealive** [comment]
Nice, thanks alot @kevinmatthes !
